Repository raphaelmue/travlyn, pull requests merged in 2020-05, with the labels that each got.

#71 Reorder Allowed option (TSP)
  docs/work/content/03_listings/abkuerzungen.tex
  docs/work/content/04_content/datengrundlage.tex
  docs/work/content/04_content/implementierung.tex
  docs/work/content/Travlyn.ctv6
  docs/work/content/literatur.bib
  docs/work/work.pdf
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRouteTripDirectionRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TSPSolver.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TravlynService.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/OpenRouteDirectionsTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/service/TSPSolverTest.java
  java/org.travlyn.server/src/test/resources/org/travlyn/server/service/example-tsp.txt
Labels: feature

#86 Refactoring to pass quality gate
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/ApiException.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/ApiOriginFilter.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/CityApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/StopApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/StopApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/UserApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/UserApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/configuration/HomeController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/APIRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaStopRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRouteDirectionRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/Request.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/WikimediaRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TravlynService.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/api/TripControllerTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/api/UserControllerTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/WikimediaAccessTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/service/TravlynServiceTest.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/City.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/CityEntity.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/Location.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/StopEntity.java
  prototyping/.idea/.gitignore
  prototyping/.idea/.name
  prototyping/.idea/compiler.xml
  prototyping/.idea/encodings.xml
  prototyping/.idea/misc.xml
  prototyping/.idea/prototyping.iml
  prototyping/.idea/vcs.xml
  prototyping/prototyping.iml
  prototyping/src/main/resources/de/travlyn/prototyping/Foursquare.txt
  prototyping/src/main/resources/de/travlyn/prototyping/OpenRouteService.txt
  prototyping/target/classes/de/travlyn/prototyping/APIRequest.class
  prototyping/target/classes/de/travlyn/prototyping/Foursquare.txt
  prototyping/target/classes/de/travlyn/prototyping/OpenRouteService.txt
  prototyping/target/classes/de/travlyn/prototyping/ParameterStringBuilder.class
  prototyping/target/classes/de/travlyn/prototyping/Test.class
  prototyping/target/de.travlyn.prototype-1.0-SNAPSHOT.jar
  prototyping/target/maven-archiver/pom.properties
  prototyping/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  prototyping/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  prototyping/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
Labels: code improvement, test

#69 See More functionality
  android/app/src/main/java/org/travlyn/api/model/City.kt
  android/app/src/main/java/org/travlyn/ui/home/HomeFragment.kt
  android/app/src/main/java/org/travlyn/ui/home/StopsActivity.kt
  android/app/src/main/res/layout/activity_stops.xml
  android/app/src/main/res/values-de/strings.xml
  android/app/src/main/res/values/strings.xml
Labels: enhancement

#94 Preferences for users
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/UserApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaStopRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TravlynService.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/api/UserControllerTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/service/TravlynServiceTest.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/City.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/Preference.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/User.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/CityEntity.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/PreferenceEntity.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/UserEntity.java
Labels: feature
