Repository raphaelmue/travlyn, pull requests merged in 2020-04, with the labels that each got.

#44 Ausblick & osmdroid (Closes #28)
  docs/work/content/04_content/datengrundlage.tex
  docs/work/content/04_content/einleitung.tex
  docs/work/content/04_content/konzept.tex
  docs/work/content/04_content/voraussetzungen.tex
  docs/work/content/Travlyn.ctv6
  docs/work/content/literatur.bib
  docs/work/work.pdf
Labels: documentation

#60 Issue52
  java/.gitignore
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaCityRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaStopRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRouteRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/QuotaLimitException.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/Request.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TravlynService.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/DBpediaAccessTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/DBpediaStopRequestTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/OpenRouteStopAccessTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/service/TravlynServiceTest.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/City.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/CityEntity.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/StopEntity.java
Labels: bug

#58 Implementation chapter
  docs/work/code/CityApi.java
  docs/work/content/03_listings/abkuerzungen.tex
  docs/work/content/04_content/implementierung.tex
  docs/work/images/authorization-flow-chart.drawio
  docs/work/images/authorization-flow-chart.pdf
  docs/work/work.pdf
Labels: documentation

#62 Trip route endpoints
  Jenkinsfile
  java/.gitignore
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaCityRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaStopRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRouteDirectionRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRoutePOIRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRouteRedirectionRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRouteTripDirectionRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TravlynService.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/OpenRouteDirectionsTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/OpenRouteStopAccessTest.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/ExecutionInfo.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/Step.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/Stop.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/Trip.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/Waypoint.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/TripEntity.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/TripStopEntity.java
Labels: feature

#53 Issues #23, #22, #33
  android/app/src/androidTest/java/org/travlyn/ExampleInstrumentedTest.kt
  android/app/src/main/java/org/travlyn/MainActivity.kt
  android/app/src/main/java/org/travlyn/api/CityApi.kt
  android/app/src/main/java/org/travlyn/api/StopApi.kt
  android/app/src/main/java/org/travlyn/api/TripApi.kt
  android/app/src/main/java/org/travlyn/api/UserApi.kt
  android/app/src/main/java/org/travlyn/infrastructure/ApiClient.kt
  android/app/src/main/java/org/travlyn/infrastructure/error/Exceptions.kt
  android/app/src/main/java/org/travlyn/local/Application.kt
  android/app/src/main/java/org/travlyn/local/Formatter.kt
  android/app/src/main/java/org/travlyn/local/LocalStorage.kt
  android/app/src/main/java/org/travlyn/ui/home/HomeFragment.kt
  android/app/src/main/java/org/travlyn/ui/home/StopsActivity.kt
  android/app/src/main/java/org/travlyn/ui/home/Suggestion.kt
  android/app/src/main/java/org/travlyn/ui/login/LoginActivity.kt
  android/app/src/main/java/org/travlyn/ui/settings/SettingsFragment.kt
  android/app/src/main/java/org/travlyn/ui/trips/CreateTripActivity.kt
  android/app/src/main/java/org/travlyn/ui/trips/TripInformationActivity.kt
  android/app/src/main/java/org/travlyn/ui/trips/TripsFragment.kt
  android/app/src/main/res/anim/slide_out_right.xml
  android/app/src/main/res/drawable-anydpi/ic_add.xml
  android/app/src/main/res/drawable-anydpi/ic_chevron_right.xml
  android/app/src/main/res/drawable-anydpi/ic_error.xml
  android/app/src/main/res/drawable-anydpi/ic_favorite_border.xml
  android/app/src/main/res/drawable-anydpi/ic_location.xml
  android/app/src/main/res/drawable-anydpi/ic_location_marker.xml
  android/app/src/main/res/drawable-anydpi/ic_money.xml
  android/app/src/main/res/drawable-anydpi/ic_search.xml
  android/app/src/main/res/drawable-anydpi/ic_settings.xml
  android/app/src/main/res/drawable-anydpi/ic_tag.xml
  android/app/src/main/res/drawable-anydpi/ic_time.xml
  android/app/src/main/res/drawable-anydpi/ic_user.xml
  android/app/src/main/res/drawable/gradient_app_bar.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_settings.xml
  android/app/src/main/res/layout/nav_header_main.xml
  android/app/src/main/res/layout/stop_card_view.xml
  android/app/src/main/res/menu/main.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/navigation/mobile_navigation.xml
  android/app/src/main/res/values-de/strings.xml
  android/app/src/main/res/values/strings.xml
  java/org.travlyn.server/pom.xml
  java/org.travlyn.server/src/main/java/org/travlyn/server/TravlynServer.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/StopApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/UserApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/configuration/AuthenticationTokenFilter.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/configuration/CustomInstantDeserializer.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/configuration/PersistenceConfiguration.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/configuration/WebSecurityConfiguration.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TravlynService.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/service/TravlynServiceTest.java
Labels: bug, code improvement, enhancement

#77 Hotfix: Authentication
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/StopApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/UserApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/configuration/AuthenticationTokenFilter.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/configuration/WebSecurityConfiguration.java
Labels: bug

#63 Continued implementation chapter
  docs/work/content/03_listings/abkuerzungen.tex
  docs/work/content/04_content/datengrundlage.tex
  docs/work/content/04_content/einleitung.tex
  docs/work/content/04_content/implementierung.tex
  docs/work/content/Travlyn.ctv6
  docs/work/content/literatur.bib
  docs/work/images/DBpediaFlow.pdf
  docs/work/images/DBpediaFlow.xml
  docs/work/work.pdf
Labels: documentation

#79 Issue78
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaStopRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRouteDirectionRequest.java
Labels: bug

#70 Mocking of API Tests
  java/org.travlyn.server/pom.xml
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/APIRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaCityRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaStopRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRouteDirectionRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/OpenRoutePOIRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/QuotaLimitException.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/ApiTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/DBpediaAccessTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/DBpediaStopRequestTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/OpenRouteDirectionsTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/OpenRouteStopAccessTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/service/TravlynServiceTest.java
  java/org.travlyn.server/src/test/resources/org/travlyn/server/dbpedia-response-empty.json
  java/org.travlyn.server/src/test/resources/org/travlyn/server/dbpedia-response-karlsruhe.json
  java/org.travlyn.server/src/test/resources/org/travlyn/server/dbpedia-response-karlsruhe_palace.json
  java/org.travlyn.server/src/test/resources/org/travlyn/server/dbpedia-stop-response-admirality-arch.json
  java/org.travlyn.server/src/test/resources/org/travlyn/server/openroute-poi-response.json
  java/org.travlyn.server/src/test/resources/org/travlyn/server/openroute-response-karlsruhe-empty.json
  java/org.travlyn.server/src/test/resources/org/travlyn/server/openroute-response-karlsruhe.json
  java/org.travlyn.server/src/test/resources/org/travlyn/server/openroute-response-redirection.json
  java/org.travlyn.server/src/test/resources/org/travlyn/server/openroute-response-triproute.json
Labels: test

#68 Remaining endpoints for trip execution
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/StopApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/StopApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApi.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/api/TripApiController.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TravlynService.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/ValueException.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/service/TravlynServiceTest.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/api/Trip.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/StopEntity.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/TripEntity.java
  java/org.travlyn.shared/src/main/java/org/travlyn/shared/model/db/TripRatingEntity.java
Labels: feature

#85 Authentication Bug
  java/org.travlyn.server/src/main/java/org/travlyn/server/configuration/AuthenticationTokenFilter.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/service/TravlynService.java
Labels: bug

#89 Bugs
  android/app/src/main/java/org/travlyn/ui/login/RegisterActivity.kt
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaCityRequest.java
  java/org.travlyn.server/src/main/java/org/travlyn/server/externalapi/access/DBpediaStopRequest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/DBpediaAccessTest.java
  java/org.travlyn.server/src/test/java/org/travlyn/server/externalapi/access/DBpediaStopRequestTest.java
Labels: bug

#83 First part of evaluation chapter
  docs/work/content/03_listings/abkuerzungen.tex
  docs/work/content/04_content/anforderungen.tex
  docs/work/content/04_content/evaluation.tex
  docs/work/content/04_content/implementierung.tex
  docs/work/content/Travlyn.ctv6
  docs/work/content/literatur.bib
  docs/work/work.pdf
Labels: documentation
